CREATE TABLE `node`.`MEMO`
(
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`AUTHOR` VARCHAR(32) NULL DEFAULT NULL,
	`CONTENTS` TEXT NULL,
	`CREATEDATE` VARCHAR(16) NULL DEFAULT NULL,
	`FILENAME` TEXT NULL,
	PRIMARY KEY (`ID`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;